// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqmuflcwmseyxkskyiwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xbXVmbGN3bXNleXhrc2t5aXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2OTgxMjgsImV4cCI6MjA1MzI3NDEyOH0.htPZa9pnktxZNhFiQ4jfG4pk6amTh3MQs4UTVTud4ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);